@url=http://localhost:9002
@sessionid=5f09554658a68ea7ab11597d

###
GET {{url}}

###

GET {{url}}/session


###

GET {{url}}/session/{{sessionid}}

###

POST {{url}}/session

###
DELETE {{url}}/session/{{sessionid}}