@url=http://localhost:9002
@sessionid=5f0aa1d55687635e34925f9d

###
GET {{url}}

###

GET {{url}}/session


###

GET {{url}}/session/{{sessionid}}

###

POST {{url}}/session

###
DELETE {{url}}/session/{{sessionid}}

###
### Rolls
###

GET {{url}}/roll/{{sessionid}}/Darkops

###
POST {{url}}/roll/{{sessionid}}/Darkops/100

###
DELETE {{url}}/roll/5f0aa1ee5687635e34925fa3