@url=http://localhost:9002
@sessionid=5f0a05a1a7e8f1b3ddc9bae1

###
GET {{url}}

###

GET {{url}}/session


###

GET {{url}}/session/{{sessionid}}

###

POST {{url}}/session

###
DELETE {{url}}/session/{{sessionid}}

###
### Rolls
###

GET {{url}}/roll/{{sessionid}}/Darkops

###
POST {{url}}/roll/{{sessionid}}/Darkops/100

###
DELETE {{url}}/roll/5f0b5589bc07bbcfb2c41a75